// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responseMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_responseMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_responseMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_responseMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_responseMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_responseMessage_2eproto;
namespace autel {
namespace protocol {
class responseMessage;
struct responseMessageDefaultTypeInternal;
extern responseMessageDefaultTypeInternal _responseMessage_default_instance_;
}  // namespace protocol
}  // namespace autel
PROTOBUF_NAMESPACE_OPEN
template<> ::autel::protocol::responseMessage* Arena::CreateMaybeMessage<::autel::protocol::responseMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace autel {
namespace protocol {

enum errorCode : int {
  ERR_NONE = 0,
  ERR_SIGN = 1,
  ERR_SRCH = 2,
  ERR_DEST = 3,
  ERR_NXIO = 4,
  ERR_NODEV = 5,
  ERR_NOSPC = 6,
  ERR_NOENT = 7,
  ERR_READY = 8,
  ERR_EXIST = 9,
  ERR_ISDIR = 10,
  ERR_ENCRY = 11,
  ERR_DECRY = 12,
  ERR_ISFILE = 13,
  ERR_DAMAGE = 14,
  ERR_NOTDIR = 15,
  ERR_NOTFILE = 16,
  ERR_IO = 30,
  ERR_PERM = 31,
  ERR_FBIG = 32,
  ERR_ROFS = 33,
  ERR_AGAIN = 34,
  ERR_NOMEM = 35,
  ERR_INVAL = 36,
  ERR_BUSY = 37,
  ERR_REFUSE = 38,
  ERR_TIMEOUT = 39,
  ERR_SUPPORT = 40,
  ERR_SERVICE = 41,
  errorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  errorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool errorCode_IsValid(int value);
constexpr errorCode errorCode_MIN = ERR_NONE;
constexpr errorCode errorCode_MAX = ERR_SERVICE;
constexpr int errorCode_ARRAYSIZE = errorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* errorCode_descriptor();
template<typename T>
inline const std::string& errorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, errorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function errorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    errorCode_descriptor(), enum_t_value);
}
inline bool errorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, errorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<errorCode>(
    errorCode_descriptor(), name, value);
}
// ===================================================================

class responseMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:autel.protocol.responseMessage) */ {
 public:
  inline responseMessage() : responseMessage(nullptr) {}
  ~responseMessage() override;
  explicit PROTOBUF_CONSTEXPR responseMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  responseMessage(const responseMessage& from);
  responseMessage(responseMessage&& from) noexcept
    : responseMessage() {
    *this = ::std::move(from);
  }

  inline responseMessage& operator=(const responseMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline responseMessage& operator=(responseMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const responseMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const responseMessage* internal_default_instance() {
    return reinterpret_cast<const responseMessage*>(
               &_responseMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(responseMessage& a, responseMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(responseMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(responseMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  responseMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<responseMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const responseMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const responseMessage& from) {
    responseMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(responseMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "autel.protocol.responseMessage";
  }
  protected:
  explicit responseMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrDescFieldNumber = 3,
    kDataFieldNumber = 4,
    kResultFieldNumber = 1,
    kErrCodeFieldNumber = 2,
  };
  // string errDesc = 3;
  void clear_errdesc();
  const std::string& errdesc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errdesc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errdesc();
  PROTOBUF_NODISCARD std::string* release_errdesc();
  void set_allocated_errdesc(std::string* errdesc);
  private:
  const std::string& _internal_errdesc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errdesc(const std::string& value);
  std::string* _internal_mutable_errdesc();
  public:

  // .google.protobuf.Any data = 4;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const ::PROTOBUF_NAMESPACE_ID::Any& data() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Any* release_data();
  ::PROTOBUF_NAMESPACE_ID::Any* mutable_data();
  void set_allocated_data(::PROTOBUF_NAMESPACE_ID::Any* data);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Any& _internal_data() const;
  ::PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_data();
  public:
  void unsafe_arena_set_allocated_data(
      ::PROTOBUF_NAMESPACE_ID::Any* data);
  ::PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_data();

  // int32 result = 1;
  void clear_result();
  int32_t result() const;
  void set_result(int32_t value);
  private:
  int32_t _internal_result() const;
  void _internal_set_result(int32_t value);
  public:

  // int32 errCode = 2;
  void clear_errcode();
  int32_t errcode() const;
  void set_errcode(int32_t value);
  private:
  int32_t _internal_errcode() const;
  void _internal_set_errcode(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:autel.protocol.responseMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errdesc_;
    ::PROTOBUF_NAMESPACE_ID::Any* data_;
    int32_t result_;
    int32_t errcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_responseMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// responseMessage

// int32 result = 1;
inline void responseMessage::clear_result() {
  _impl_.result_ = 0;
}
inline int32_t responseMessage::_internal_result() const {
  return _impl_.result_;
}
inline int32_t responseMessage::result() const {
  // @@protoc_insertion_point(field_get:autel.protocol.responseMessage.result)
  return _internal_result();
}
inline void responseMessage::_internal_set_result(int32_t value) {
  
  _impl_.result_ = value;
}
inline void responseMessage::set_result(int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:autel.protocol.responseMessage.result)
}

// int32 errCode = 2;
inline void responseMessage::clear_errcode() {
  _impl_.errcode_ = 0;
}
inline int32_t responseMessage::_internal_errcode() const {
  return _impl_.errcode_;
}
inline int32_t responseMessage::errcode() const {
  // @@protoc_insertion_point(field_get:autel.protocol.responseMessage.errCode)
  return _internal_errcode();
}
inline void responseMessage::_internal_set_errcode(int32_t value) {
  
  _impl_.errcode_ = value;
}
inline void responseMessage::set_errcode(int32_t value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:autel.protocol.responseMessage.errCode)
}

// string errDesc = 3;
inline void responseMessage::clear_errdesc() {
  _impl_.errdesc_.ClearToEmpty();
}
inline const std::string& responseMessage::errdesc() const {
  // @@protoc_insertion_point(field_get:autel.protocol.responseMessage.errDesc)
  return _internal_errdesc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void responseMessage::set_errdesc(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errdesc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:autel.protocol.responseMessage.errDesc)
}
inline std::string* responseMessage::mutable_errdesc() {
  std::string* _s = _internal_mutable_errdesc();
  // @@protoc_insertion_point(field_mutable:autel.protocol.responseMessage.errDesc)
  return _s;
}
inline const std::string& responseMessage::_internal_errdesc() const {
  return _impl_.errdesc_.Get();
}
inline void responseMessage::_internal_set_errdesc(const std::string& value) {
  
  _impl_.errdesc_.Set(value, GetArenaForAllocation());
}
inline std::string* responseMessage::_internal_mutable_errdesc() {
  
  return _impl_.errdesc_.Mutable(GetArenaForAllocation());
}
inline std::string* responseMessage::release_errdesc() {
  // @@protoc_insertion_point(field_release:autel.protocol.responseMessage.errDesc)
  return _impl_.errdesc_.Release();
}
inline void responseMessage::set_allocated_errdesc(std::string* errdesc) {
  if (errdesc != nullptr) {
    
  } else {
    
  }
  _impl_.errdesc_.SetAllocated(errdesc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errdesc_.IsDefault()) {
    _impl_.errdesc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:autel.protocol.responseMessage.errDesc)
}

// .google.protobuf.Any data = 4;
inline bool responseMessage::_internal_has_data() const {
  return this != internal_default_instance() && _impl_.data_ != nullptr;
}
inline bool responseMessage::has_data() const {
  return _internal_has_data();
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& responseMessage::_internal_data() const {
  const ::PROTOBUF_NAMESPACE_ID::Any* p = _impl_.data_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Any&>(
      ::PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& responseMessage::data() const {
  // @@protoc_insertion_point(field_get:autel.protocol.responseMessage.data)
  return _internal_data();
}
inline void responseMessage::unsafe_arena_set_allocated_data(
    ::PROTOBUF_NAMESPACE_ID::Any* data) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.data_);
  }
  _impl_.data_ = data;
  if (data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:autel.protocol.responseMessage.data)
}
inline ::PROTOBUF_NAMESPACE_ID::Any* responseMessage::release_data() {
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = _impl_.data_;
  _impl_.data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* responseMessage::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_release:autel.protocol.responseMessage.data)
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = _impl_.data_;
  _impl_.data_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* responseMessage::_internal_mutable_data() {
  
  if (_impl_.data_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Any>(GetArenaForAllocation());
    _impl_.data_ = p;
  }
  return _impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* responseMessage::mutable_data() {
  ::PROTOBUF_NAMESPACE_ID::Any* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:autel.protocol.responseMessage.data)
  return _msg;
}
inline void responseMessage::set_allocated_data(::PROTOBUF_NAMESPACE_ID::Any* data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.data_);
  }
  if (data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(data));
    if (message_arena != submessage_arena) {
      data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.data_ = data;
  // @@protoc_insertion_point(field_set_allocated:autel.protocol.responseMessage.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace autel

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::autel::protocol::errorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::autel::protocol::errorCode>() {
  return ::autel::protocol::errorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_responseMessage_2eproto
